name: flutter_livraison_restoration
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.18.0


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  cloud_firestore: ^3.1.18
  country_code_picker: ^2.0.2
  firebase_auth: ^3.4.1
  flutter_spinkit: ^5.1.0
  email_validator: ^2.0.1
  file_picker: ^3.0.4
  firebase_storage: ^10.3.1
  location: ^4.4.0
  carousel_slider: ^4.1.1
  font_awesome: ^5.10.1
  awesome_icons: ^1.1.0
  shimmer: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true
  assets:
    - lib/images/boisson.jpg
    - lib/images/dessert.jpg
    - lib/images/resistance.jpg
    - lib/images/resistance2.jpg
    - lib/images/entree.jpg

